### ISSUE TITLE
Youtube Video Player

### ISSUE THREAD

**Issue by vikassaini** [lzls/Videos#10]
this is just feature request that play YouTube videos with this app.

**Comment by lzls** [comment]
This is a good suggestion，but... how to get YouTube videos for this app?

**Comment by lzls** [comment]
This feature comes now. Check out the latest commits from `dev` branch. @vikassaini

**Comment by vikassaini** [comment]
It nice to get this feature on app.
Some improvement needed .
1) youtube video play in different player. Is it not possible to play youtube video like local video player ?
2) need some stability in app. Online video fragments hang some time also show some errors.

**Comment by lzls** [comment]
Hi there~, thanks for your testing.
As for your first suggestion，I might try doing a lot of further work to make playing youtube videos with the original video player UI possible.
To the second, I now have published a new [signed app (version 2.1-beta01)](https://raw.githubusercontent.com/ApksHolder/Videos/beta/app_v2.1-beta01.apk), where any future crashes will report to me. If you continuously use this app，you are supposed to switch to that one or any of the later signed apks.

**Comment by lzls** [comment]
Hey @vikassaini I switched to watching YouTube videos with the default watch url so that more info we can get and more things we can do like check the comments. You can have an experience on [Videos (version 2.1-beta02)](https://raw.githubusercontent.com/ApksHolder/Videos/beta/app_v2.1-beta02.apk), since which version I also enabled the engine option VLC MediaPlayer for local & non-YouTube online video playbacks.

**Comment by vikassaini** [comment]
Latest beta update version 2.1-beta02 youtube video playback not working. It open default youtube webview within video app. 

When we shift to local vidoe playback . use of VLC player is working fine.

**Comment by lzls** [comment]
Opening the default YouTube watch page is designed so,  because I have changed the behavior as to playing YouTube videos since this beta version release, where more info we can get and more ops we can perform (especially to check the video comments).

**Comment by lzls** [comment]
Opening the default YouTube watch page is designed so, because I have changed the behavior as to playing YouTube videos since this beta version release. However, we can also control the video playback through notification action icons and this is of better support for fullscreen mode as the video can now be switched between portrait and landscape.

**Comment by vikassaini** [comment]
Now watch video in online mod is not good. It is better when  video is default  play with local player. Without youtube like interface.

**Comment by lzls** [comment]
@vikassaini It's difficult to play a YouTube video with the local media player instead of the JavaScript API based web player unless we fetch the visual and audio contents first, which are completely separate as to high resolution video sources. And I think this is not a good mean to play YouTube videos, as we will lose a lot of info from the original watch page. For behavior adaptation, I added an option for you to switch to the web player used in `Videos_v2.1-beta01.apk`.  And for test convenience, beta versions are available within the app from this version ([v2.1-beta03](https://gitlab.com/lzls/Videos-Server/-/raw/master/app/Android/Videos_v2.1-beta03.apk)) as long as you select the update channel to at least `beta` on the app settings screen.

**Comment by vikassaini** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor 
you can use this library to extract YouTube video stream and other useful video information.
