### ISSUE TITLE
Some video info not showing. 

### ISSUE THREAD

**Issue by AdityaMishra135** [lzls/Videos#16]
![Uploading Screenshot_20220329_114218.png…]()

**Comment by lzls** [comment]
what info? @AdityaMishra135

**Comment by AdityaMishra135** [comment]
![Screenshot_20220329_114218](https://user-images.githubusercontent.com/94228705/160568014-c5c7cd8a-4f19-4896-a75c-a65de1172433.png)

**Comment by lzls** [comment]
This is normal. The video info is first fetched from the system media database, some of which may not have been recorded. In this case the app will try fetching the info via MediaMetadataRetriever then record them into the db once for all.  But if the info is failed to fetch, default data will be displayed for the lacked info of a video. This is not so important that we can retry with more approaches despite the performance influcence unless we have a better choice instead of MediaMetadataRetriever.

**Comment by AdityaMishra135** [comment]
Whats better instead of media metadat
